name: Nebula
version: dev
slug: nebula
description: HomeAssistant addon for slackhq/nebula
url: https://github.com/mr-ransel/addon-nebula
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  4242/udp: 4242
ports_description:
  4242/udp: "Nebula: This is the port used for encrypted traffic from inside the docker container"
hassio_api: false
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
options:
  addon_node_name: homeassistant
  addon_is_lighthouse: false
  addon_advertise_addrs: []
  other_lighthouses: []
  preferred_route_cidrs: []
schema:
  addon_node_name: str
  addon_is_lighthouse: bool
  advertise_addrs:
    - "match(^[-0-9a-z\\.]+:\\d{1,5}$)" # Must be a IP/domain:port
  other_lighthouses:
  - overlay_ip: "match(^(([1-9]?\\d|1\\d\\d|25[0-5]|2[0-4]\\d)\\.){3}([1-9]?\\d|1\\d\\d|25[0-5]|2[0-4]\\d)$)" # Must be an IP address
    public_addr_and_port: "match(^[-0-9a-z\\.]+:\\d{1,5}$)" # Must be an IP/hostname:port
  preferred_route_cidrs:
    - "match(^(([1-9]?\\d|1\\d\\d|25[0-5]|2[0-4]\\d)\\.){3}([1-9]?\\d|1\\d\\d|25[0-5]|2[0-4]\\d)/\\d{1,2}$)" # Must be an IP address and CIDR range
